"""Add title to note

Revision ID: 0f740ebb5890
Revises: 0b754bd8cf2c
Create Date: 2025-04-29 22:58:26.065648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f740ebb5890'
down_revision: Union[str, None] = '0b754bd8cf2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_diseases', sa.Column('prediction_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_diseases', 'prediction_date')
    # ### end Alembic commands ###
