"""initial migration

Revision ID: 1730344ca1d2
Revises: 
Create Date: 2025-01-22 21:25:20.468862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1730344ca1d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('taps_for_level', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('money', sa.Float(), nullable=False),
    sa.Column('current_factor', sa.Float(), nullable=False),
    sa.Column('invited_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('received_last_daily_reward', sa.DateTime(), nullable=False),
    sa.Column('days_in_row', sa.Integer(), nullable=False),
    sa.Column('number_of_columns_passed', sa.BigInteger(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_tg_id'], ['user.tg_id'], ),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
