"""add password_hash column

Revision ID: 6feb1203ac11
Revises: e39a02a26d90
Create Date: 2025-01-28 21:45:43.916801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6feb1203ac11'
down_revision: Union[str, None] = 'e39a02a26d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_users_is_online', table_name='users')
    op.drop_index('ix_users_nickname', table_name='users')
    op.create_unique_constraint(None, 'users', ['tg_id'])
    op.drop_column('users', 'is_online')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'imageURL')
    op.drop_column('users', 'surname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('imageURL', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_nickname', 'users', ['nickname'], unique=True)
    op.create_index('ix_users_is_online', 'users', ['is_online'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'tg_id')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
